# Generated by Django 4.0.3 on 2022-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_importer', models.FileField(blank=True, upload_to='csv')),
            ],
        ),
    ]
