# Generated by Django 4.0.3 on 2022-06-07 19:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=30)),
                ('agencia_origem', models.CharField(max_length=30)),
                ('conta_origem', models.CharField(max_length=30)),
                ('banco_destino', models.CharField(max_length=30)),
                ('agencia_destino', models.CharField(max_length=30)),
                ('conta_destino', models.CharField(max_length=30)),
                ('valor_da_transacao', models.FloatField(max_length=200)),
                ('data_e_hora_da_transacao', models.DateField()),
                ('data_publicacao_banco', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao_banco', models.DateField(default=datetime.datetime.now)),
                ('data_transacao_banco', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
