# Generated by Django 4.0.3 on 2022-04-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=30)),
                ('agencia_origem', models.CharField(max_length=30)),
                ('conta_origem', models.CharField(max_length=30)),
                ('banco_destino', models.CharField(max_length=30)),
                ('agencia_destino', models.CharField(max_length=30)),
                ('conta_destino', models.CharField(max_length=30)),
                ('valor_da_transacao', models.FloatField(max_length=200)),
                ('data_e_hora_da_transacao', models.DateTimeField()),
            ],
        ),
    ]
