# Generated by Django 4.0.3 on 2022-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomovimento',
            name='arquivo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
