# Generated by Django 4.0.3 on 2022-06-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentos',
            old_name='usuario',
            new_name='ordem_lancamento',
        ),
    ]
