# Generated by Django 4.0.3 on 2022-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_alter_modelomovimento_data_e_hora_da_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomovimento',
            name='data_e_hora_da_transacao',
            field=models.DateTimeField(),
        ),
    ]
