# Generated by Django 4.0.3 on 2022-05-21 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0003_remove_modelomovimento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomovimento',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
