# Generated by Django 4.0.3 on 2022-05-23 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0004_modelomovimento_data_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_transacao', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='modelomovimento',
            name='data_publicacao',
        ),
    ]
