# Generated by Django 4.0.3 on 2022-06-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0008_alter_arquivo_usuario_alter_modelomovimento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelomovimento',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
